import type { EvolutionArchetype } from "./evolutionGenerator";

/**
 * Warrior-style auto-naming for evolution lineages.
 *
 * Names follow the rank progression of a line: the starter is a kit
 * ("Emberkit"), stage I an apprentice ("Emberpaw"), stage II a warrior with
 * a rolled suffix ("Emberheart"), and stage III a leader ("Emberstar").
 * Each line draws its prefix from its clan's themed pool; prefixes and
 * warrior suffixes are unique within a batch so a lineage never collides
 * with itself.
 */

export type LineageNameInput = {
  key: string;
  level: number;
  branchLabel: string | null;
  archetype: string | null;
};

const CLAN_PREFIXES: Record<EvolutionArchetype, string[]> = {
  flare: [
    "Ember",
    "Blaze",
    "Flame",
    "Cinder",
    "Ash",
    "Scorch",
    "Spark",
    "Flare",
    "Burn",
    "Smoke",
    "Char",
    "Fox",
    "Russet",
    "Amber",
    "Crimson",
    "Lava",
    "Pyre",
    "Kindle",
    "Torch",
    "Coal",
    "Singe",
    "Molten",
    "Phoenix",
    "Dragon",
    "Sear",
    "Flicker",
    "Scarlet",
    "Brand",
    "Fire",
    "Red",
    "Copper",
    "Rust",
    "Glow",
    "Heat",
  ],
  aqua: [
    "Wave",
    "Tide",
    "River",
    "Brook",
    "Stream",
    "Splash",
    "Ripple",
    "Mist",
    "Rain",
    "Puddle",
    "Lake",
    "Marsh",
    "Reed",
    "Minnow",
    "Trout",
    "Salmon",
    "Pike",
    "Otter",
    "Heron",
    "Gull",
    "Pearl",
    "Coral",
    "Kelp",
    "Foam",
    "Drift",
    "Current",
    "Deep",
    "Blue",
    "Azure",
    "Dew",
    "Shell",
    "Fin",
    "Eel",
    "Frog",
    "Pond",
  ],
  leaf: [
    "Leaf",
    "Fern",
    "Moss",
    "Bramble",
    "Thorn",
    "Oak",
    "Birch",
    "Willow",
    "Cedar",
    "Pine",
    "Maple",
    "Alder",
    "Hazel",
    "Holly",
    "Ivy",
    "Root",
    "Bark",
    "Acorn",
    "Beech",
    "Sorrel",
    "Nettle",
    "Clover",
    "Sage",
    "Juniper",
    "Aspen",
    "Elm",
    "Sprout",
    "Seed",
    "Grove",
    "Wild",
    "Deer",
    "Doe",
    "Stag",
    "Squirrel",
    "Toad",
  ],
  sun: [
    "Sun",
    "Gold",
    "Golden",
    "Honey",
    "Dawn",
    "Day",
    "Morning",
    "Bright",
    "Light",
    "Shine",
    "Ray",
    "Gleam",
    "Glimmer",
    "Marigold",
    "Saffron",
    "Wheat",
    "Straw",
    "Sand",
    "Dune",
    "Dust",
    "Lion",
    "Daisy",
    "Sunny",
    "Topaz",
    "Halo",
    "Noon",
    "Summer",
    "Harvest",
    "Maize",
    "Canary",
    "Lemon",
    "Apricot",
  ],
  rose: [
    "Rose",
    "Petal",
    "Blossom",
    "Bloom",
    "Flower",
    "Briar",
    "Cherry",
    "Peach",
    "Berry",
    "Poppy",
    "Tulip",
    "Lily",
    "Orchid",
    "Primrose",
    "Blush",
    "Pink",
    "Fuchsia",
    "Dahlia",
    "Peony",
    "Camellia",
    "Azalea",
    "Mallow",
    "Heather",
    "Fawn",
    "Robin",
    "Wren",
    "Sweet",
    "Silk",
    "Velvet",
    "Thistle",
    "Lavender",
    "Nectar",
    "Meadow",
  ],
  moon: [
    "Moon",
    "Night",
    "Silver",
    "Frost",
    "Ice",
    "Snow",
    "Cloud",
    "Sky",
    "Dusk",
    "Twilight",
    "Eclipse",
    "Comet",
    "Aurora",
    "Pale",
    "Grey",
    "Owl",
    "Dove",
    "Swan",
    "Wisp",
    "Dream",
    "Quiet",
    "Hush",
    "Winter",
    "Polar",
    "Glacier",
    "Crescent",
    "Shimmer",
    "Sleet",
    "Hail",
    "Chill",
    "Cold",
    "Misty",
  ],
  volt: [
    "Bolt",
    "Storm",
    "Thunder",
    "Lightning",
    "Flash",
    "Shock",
    "Static",
    "Surge",
    "Jolt",
    "Charge",
    "Buzz",
    "Crackle",
    "Arc",
    "Neon",
    "Wire",
    "Circuit",
    "Volt",
    "Pulse",
    "Glitch",
    "Pixel",
    "Laser",
    "Plasma",
    "Ion",
    "Strobe",
    "Dynamo",
    "Zigzag",
    "Zap",
    "Watt",
    "Amp",
    "Fuse",
    "Tempest",
    "Rumble",
  ],
  crystal: [
    "Crystal",
    "Gem",
    "Jewel",
    "Prism",
    "Quartz",
    "Amethyst",
    "Opal",
    "Diamond",
    "Sapphire",
    "Emerald",
    "Jade",
    "Beryl",
    "Garnet",
    "Glass",
    "Mirror",
    "Shard",
    "Facet",
    "Glitter",
    "Sparkle",
    "Luster",
    "Geode",
    "Citrine",
    "Zircon",
    "Agate",
    "Lapis",
    "Ruby",
    "Iris",
    "Gloss",
    "Sheen",
    "Dazzle",
    "Radiant",
    "Gemma",
  ],
  void: [
    "Shadow",
    "Dark",
    "Black",
    "Raven",
    "Crow",
    "Shade",
    "Gloom",
    "Murk",
    "Phantom",
    "Ghost",
    "Spectre",
    "Wraith",
    "Echo",
    "Hollow",
    "Abyss",
    "Obsidian",
    "Pitch",
    "Ink",
    "Soot",
    "Umbra",
    "Veil",
    "Whisper",
    "Silent",
    "Midnight",
    "Curse",
    "Hex",
    "Omen",
    "Rift",
    "Void",
    "Grim",
    "Nether",
    "Dread",
  ],
  steel: [
    "Steel",
    "Iron",
    "Brass",
    "Bronze",
    "Chrome",
    "Anvil",
    "Hammer",
    "Forge",
    "Blade",
    "Edge",
    "Spike",
    "Nail",
    "Gear",
    "Cog",
    "Rivet",
    "Shield",
    "Armor",
    "Granite",
    "Stone",
    "Rock",
    "Flint",
    "Slate",
    "Pewter",
    "Titan",
    "Alloy",
    "Ingot",
    "Tin",
    "Zinc",
    "Metal",
    "Smith",
    "Mallet",
    "Girder",
  ],
};

/** Starter kits draw from this softer, kit-flavoured pool. */
const GENERAL_PREFIXES: string[] = [
  "Tiny",
  "Little",
  "Small",
  "Young",
  "Swift",
  "Quick",
  "Soft",
  "Fuzzy",
  "Patch",
  "Spot",
  "Dot",
  "Dapple",
  "Speckle",
  "Mottle",
  "Tabby",
  "Pounce",
  "Tumble",
  "Bounce",
  "Scamper",
  "Wiggle",
  "Pip",
  "Bean",
  "Button",
  "Lucky",
  "Brave",
  "Bold",
  "Happy",
  "Gentle",
  "Curious",
  "Clever",
  "Nimble",
  "Merry",
  "Pepper",
  "Cocoa",
  "Biscuit",
  "Pudding",
  "Socks",
  "Mitten",
  "Snug",
  "Whisk",
];

const WARRIOR_SUFFIXES: string[] = [
  "heart",
  "claw",
  "fang",
  "pelt",
  "tail",
  "whisker",
  "foot",
  "fur",
  "eye",
  "ear",
  "nose",
  "face",
  "stripe",
  "spot",
  "patch",
  "storm",
  "cloud",
  "wind",
  "breeze",
  "rain",
  "snow",
  "frost",
  "blaze",
  "fire",
  "shine",
  "glow",
  "gleam",
  "shimmer",
  "light",
  "shade",
  "shadow",
  "dusk",
  "dawn",
  "night",
  "song",
  "call",
  "cry",
  "howl",
  "watcher",
  "runner",
  "leap",
  "dash",
  "strike",
  "slash",
  "bite",
  "snarl",
  "growl",
  "purr",
  "dream",
  "wish",
  "spirit",
  "gaze",
  "step",
  "path",
  "feather",
  "wing",
  "flight",
  "talon",
  "branch",
  "root",
  "hollow",
  "rock",
  "stone",
  "pebble",
  "cliff",
  "ridge",
  "peak",
  "vale",
  "pool",
  "stream",
  "brook",
  "splash",
  "ripple",
  "wave",
  "petal",
  "blossom",
  "flower",
  "berry",
  "thorn",
  "bramble",
  "fern",
  "moss",
  "leaf",
];

type RandomFn = () => number;

function pickUnused(
  pool: readonly string[],
  used: Set<string>,
  random: RandomFn,
): string | null {
  const available = pool.filter((entry) => !used.has(entry.toLowerCase()));
  if (available.length === 0) return null;
  const index = Math.min(
    Math.floor(random() * available.length),
    available.length - 1,
  );
  const picked = available[index];
  used.add(picked.toLowerCase());
  return picked;
}

function rankName(prefix: string, level: number, suffix: string): string {
  if (level <= 0) return `${prefix}kit`;
  if (level === 1) return `${prefix}paw`;
  if (level === 2) return `${prefix}${suffix}`;
  return `${prefix}star`;
}

/**
 * Generate matching warrior names for a whole lineage. Returns a map from
 * cat key to name. Prefixes (per line) and warrior suffixes are unique
 * within the batch.
 */
export function generateLineageNames(
  cats: LineageNameInput[],
  random: RandomFn = Math.random,
): Map<string, string> {
  const names = new Map<string, string>();
  const usedPrefixes = new Set<string>();
  const usedSuffixes = new Set<string>();

  const starter = cats.find((cat) => cat.level === 0);
  if (starter) {
    const prefix =
      pickUnused(GENERAL_PREFIXES, usedPrefixes, random) ?? "Little";
    names.set(starter.key, `${prefix}kit`);
  }

  const branches = new Map<string, LineageNameInput[]>();
  for (const cat of cats) {
    if (cat.level <= 0 || !cat.branchLabel) continue;
    const list = branches.get(cat.branchLabel) ?? [];
    list.push(cat);
    branches.set(cat.branchLabel, list);
  }

  for (const [, lineCats] of branches) {
    const archetype = lineCats[0]?.archetype as EvolutionArchetype | null;
    const clanPool = archetype ? (CLAN_PREFIXES[archetype] ?? []) : [];
    const prefix =
      pickUnused(clanPool, usedPrefixes, random) ??
      pickUnused(GENERAL_PREFIXES, usedPrefixes, random) ??
      pickUnused(Object.values(CLAN_PREFIXES).flat(), usedPrefixes, random) ??
      "Wander";
    // The warrior suffix must not echo the prefix ("Leafleaf").
    const suffixGuard = new Set(usedSuffixes);
    suffixGuard.add(prefix.toLowerCase());
    const suffix = pickUnused(WARRIOR_SUFFIXES, suffixGuard, random) ?? "heart";
    usedSuffixes.add(suffix);

    for (const cat of lineCats) {
      names.set(cat.key, rankName(prefix, cat.level, suffix));
    }
  }

  return names;
}
