"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { Loader2 } from "lucide-react";

export type AdoptionMetadata = {
  title: string;
  creator: string;
};

export type AdoptionMetadataPanelProps = {
  savedValue: AdoptionMetadata;
  onSave: (value: AdoptionMetadata) => void;
  busy?: boolean;
  error?: string | null;
  message?: string | null;
  canSave?: boolean;
};

export function AdoptionMetadataPanel({ savedValue, onSave, busy, error, message, canSave }: AdoptionMetadataPanelProps) {
  const [title, setTitle] = useState(savedValue.title);
  const [creator, setCreator] = useState(savedValue.creator);

  useEffect(() => {
    setTitle(savedValue.title);
  }, [savedValue.title]);

  useEffect(() => {
    setCreator(savedValue.creator);
  }, [savedValue.creator]);

  const dirty = title !== savedValue.title || creator !== savedValue.creator;
  const showMessage = !dirty ? message : null;

  const handleSubmit = () => {
    onSave({ title, creator });
  };

  return (
    <div className="flex flex-col gap-4 rounded-2xl border border-border/40 bg-background/70 p-4">
      <div className="grid gap-3 md:grid-cols-2">
        <label className="flex flex-col gap-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground/70">
          <span>Batch Title</span>
          <input
            type="text"
            value={title}
            onChange={(event: ChangeEvent<HTMLInputElement>) => setTitle(event.target.value)}
            placeholder="Optional title"
            className="rounded-xl border border-border/40 bg-background px-4 py-2 text-sm text-foreground focus:border-primary focus:outline-none"
          />
        </label>
        <label className="flex flex-col gap-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground/70">
          <span>Generated By</span>
          <input
            type="text"
            value={creator}
            onChange={(event: ChangeEvent<HTMLInputElement>) => setCreator(event.target.value)}
            placeholder="Name of roller"
            className="rounded-xl border border-border/40 bg-background px-4 py-2 text-sm text-foreground focus:border-primary focus:outline-none"
          />
        </label>
      </div>
      <div className="flex flex-wrap items-center gap-3 text-xs">
        <button
          type="button"
          onClick={handleSubmit}
          disabled={busy || !canSave || !dirty}
          className="inline-flex items-center gap-2 rounded-full border border-border/50 px-4 py-2 font-semibold uppercase tracking-wide transition hover:bg-foreground hover:text-background disabled:cursor-not-allowed disabled:opacity-60"
        >
          {busy ? <Loader2 className="size-3 animate-spin" /> : null}
          Save to history
        </button>
        {showMessage ? <span className="text-emerald-300">{showMessage}</span> : null}
        {error ? <span className="text-red-300">{error}</span> : null}
      </div>
    </div>
  );
}
