// Scans app/**/widget.ts files and generates the tool registry.
// Run: bun scripts/generate-registry.ts
import { resolve, relative } from "path";

const ROOT = resolve(import.meta.dir, "..");
const OUT = resolve(ROOT, "lib/dash/registry.generated.ts");

const glob = new Bun.Glob("app/**/widget.ts");
const paths = [...glob.scanSync({ cwd: ROOT, absolute: true })].sort();

interface WidgetModule {
  default: {
    id: string;
    title: string;
    description: string;
    icon: string;
    href: string;
    category: string;
  };
}

const entries: WidgetModule["default"][] = [];

for (const abs of paths) {
  const mod = (await import(abs)) as WidgetModule;
  if (!mod.default?.id) {
    console.warn(`Skipping ${relative(ROOT, abs)}: no default export with id`);
    continue;
  }
  entries.push(mod.default);
}

entries.sort((a, b) => a.id.localeCompare(b.id));

const lines = [
  "// Auto-generated by scripts/generate-registry.ts — do not edit manually",
  'import type { ToolWidgetMeta } from "./types";',
  "",
  `export const TOOL_REGISTRY: ToolWidgetMeta[] = ${JSON.stringify(entries, null, 2)};`,
  "",
  "export const TOOL_MAP = new Map<string, ToolWidgetMeta>(",
  "  TOOL_REGISTRY.map((t) => [t.id, t]),",
  ");",
  "",
];

await Bun.write(OUT, lines.join("\n"));
console.log(`Wrote ${entries.length} tools to ${relative(ROOT, OUT)}`);
