import { z } from "zod";
import {
  booleanValue,
  defineCatSystem,
  defineCatTrait,
  objectListValue,
  stringListValue,
  stringValue,
} from "./definition";

export const CAT_SCHEMA_VERSION = 1 as const;

export const tortieLayerSchema = z.object({
  mask: z.string(),
  pattern: z.string(),
  colour: z.string(),
});

const pose = defineCatTrait({
  id: "pose",
  label: "Pose",
  order: 10,
  value: stringValue({
    required: true,
    default: "adult_short0",
    catalog: "poses",
  }),
  legacy: { strategy: "pose", key: "poseName", spriteKey: "spriteNumber" },
  render: { kind: "context" },
  gacha: { strategy: "catalogChoice", catalog: "randomPoses" },
  capabilities: {
    display: true,
    edit: "select",
    reveal: {
      strategy: "single",
      timingKey: "sprite",
      defaultSteps: 10,
      spin: { order: 140, label: "Sprite" },
    },
    evolution: "preserve",
    inherit: "none",
    settings: false,
  },
});

const pelt = defineCatTrait({
  id: "pelt",
  label: "Pelt",
  order: 20,
  value: stringValue({
    required: true,
    default: "SingleColour",
    catalog: "pelts",
  }),
  legacy: { strategy: "direct", key: "peltName" },
  render: {
    kind: "operation",
    operationId: "base",
    layerId: "base",
    strategy: "basePelt",
    version: 1,
    reads: ["pelt", "colour", "tortie"],
    config: {},
  },
  gacha: { strategy: "catalogChoice", catalog: "coatChoices" },
  capabilities: {
    display: true,
    edit: "select",
    reveal: {
      strategy: "single",
      timingKey: "pelt",
      defaultSteps: 10,
      spin: { order: 20 },
    },
    evolution: "preserve",
    inherit: "mutate",
    settings: false,
  },
});

const coatPattern = defineCatTrait({
  id: "coatPattern",
  label: "Coat pattern",
  order: 30,
  value: stringValue({ required: false, catalog: "coatPatterns" }),
  legacy: { strategy: "direct", key: "coatPattern" },
  render: {
    kind: "operation",
    operationId: "coatPattern",
    layerId: "coatPattern",
    strategy: "coatPattern",
    version: 1,
    after: ["base"],
    reads: ["coatPattern", "pelt", "colour", "tortie"],
    config: {},
  },
  gacha: {
    strategy: "derived",
    resolver: "coatChoiceProjection",
    sourceTrait: "pelt",
    dependsOn: ["pelt"],
  },
  capabilities: {
    display: true,
    edit: "select",
    reveal: false,
    evolution: "preserve",
    inherit: "mutate",
    settings: false,
  },
});

const colour = defineCatTrait({
  id: "colour",
  label: "Base colour",
  order: 40,
  value: stringValue({ required: true, default: "WHITE", catalog: "colours" }),
  legacy: { strategy: "direct", key: "colour" },
  render: { kind: "input", operationId: "base" },
  gacha: { strategy: "catalogChoice", catalog: "colours", dependsOn: ["pelt"] },
  capabilities: {
    display: true,
    edit: "select",
    reveal: {
      strategy: "single",
      timingKey: "colour",
      defaultSteps: 19,
      spin: { order: 10, label: "Colour" },
    },
    evolution: "preserve",
    inherit: "mutate",
    settings: false,
  },
});

const tortie = defineCatTrait({
  id: "tortie",
  label: "Tortie layers",
  order: 50,
  value: objectListValue({
    required: false,
    default: [],
    schema: tortieLayerSchema,
    maxItems: 10,
    unique: true,
  }),
  legacy: { strategy: "tortie" },
  render: { kind: "input", operationId: "base" },
  gacha: {
    strategy: "tortieList",
    maskCatalog: "tortieMasks",
    peltCatalog: "pelts",
    colourCatalog: "colours",
    count: {
      strategy: "weightedDiscrete",
      weights: { "1": 0.75, "2": 0.2, "3": 0.05 },
      min: 1,
      max: 3,
    },
    activationProbability: 0.5,
    fillProbability: 0.5,
    uniqueMasks: true,
    dependsOn: ["pelt", "colour"],
  },
  capabilities: {
    display: true,
    edit: "compoundList",
    reveal: {
      strategy: "compoundSlots",
      timingKey: "tortie",
      defaultSteps: 8,
      spin: { order: 50, label: "Tortie" },
    },
    evolution: "accumulate",
    inherit: "mutate",
    settings: true,
  },
});

const tint = defineCatTrait({
  id: "tint",
  label: "Tint",
  order: 60,
  value: stringValue({ required: false, default: "none", catalog: "tints" }),
  legacy: { strategy: "direct", key: "tint" },
  render: {
    kind: "operation",
    operationId: "tint",
    layerId: "tint",
    strategy: "tintMultiply",
    version: 1,
    after: ["coatPattern"],
    reads: ["tint"],
    config: {},
  },
  gacha: { strategy: "catalogChoice", catalog: "tints", dependsOn: ["colour"] },
  capabilities: {
    display: true,
    edit: "select",
    reveal: {
      strategy: "single",
      timingKey: "tint",
      defaultSteps: 8,
      spin: { order: 60 },
    },
    evolution: "replace",
    inherit: "mutate",
    settings: false,
  },
});

const whitePatches = defineCatTrait({
  id: "whitePatches",
  label: "White patches",
  order: 70,
  value: stringValue({ required: false, catalog: "whitePatches" }),
  legacy: { strategy: "direct", key: "whitePatches" },
  render: {
    kind: "operation",
    operationId: "whitePatches",
    layerId: "whitePatches",
    strategy: "spriteLayer",
    version: 1,
    after: ["tint"],
    reads: ["whitePatches", "whitePatchesTint"],
    config: {
      valueTrait: "whitePatches",
      spriteFamily: "white",
      tintTrait: "whitePatchesTint",
      tintResolver: "whitePatch",
      diagnosticPrefix: "white",
    },
  },
  gacha: {
    strategy: "catalogChoice",
    catalog: "whitePatches",
    optionalProbability: 0.5,
    dependsOn: ["colour"],
    gate: { group: "whitePatchGroup", probability: 0.5 },
  },
  capabilities: {
    display: true,
    edit: "select",
    reveal: {
      strategy: "single",
      timingKey: "whitePatches",
      defaultSteps: 10,
      spin: { order: 80, label: "White Patches" },
    },
    evolution: "replace",
    inherit: "mutate",
    settings: false,
  },
});

const points = defineCatTrait({
  id: "points",
  label: "Points",
  order: 80,
  value: stringValue({ required: false, catalog: "points" }),
  legacy: { strategy: "direct", key: "points" },
  render: {
    kind: "operation",
    operationId: "points",
    layerId: "points",
    strategy: "spriteLayer",
    version: 1,
    after: ["whitePatches"],
    reads: ["points"],
    config: {
      valueTrait: "points",
      spriteFamily: "white",
      diagnosticPrefix: "points",
    },
  },
  gacha: {
    strategy: "catalogChoice",
    catalog: "points",
    optionalProbability: 0.5,
    dependsOn: ["whitePatches"],
    gate: { group: "whitePatchGroup", probability: 0.5 },
  },
  capabilities: {
    display: true,
    edit: "select",
    reveal: {
      strategy: "single",
      timingKey: "points",
      defaultSteps: 6,
      spin: { order: 90 },
    },
    evolution: "replace",
    inherit: "mutate",
    settings: false,
  },
});

const whitePatchesTint = defineCatTrait({
  id: "whitePatchesTint",
  label: "White patch tint",
  order: 90,
  value: stringValue({ required: false, catalog: "whitePatchColours" }),
  legacy: { strategy: "direct", key: "whitePatchesTint" },
  render: { kind: "input", operationId: "whitePatches" },
  gacha: {
    strategy: "catalogChoice",
    catalog: "whitePatchColours",
    dependsOn: ["whitePatches", "tortie"],
    gate: { group: "whitePatchGroup", probability: 0.5 },
    flattenSelection: true,
    conditionalCatalogs: [
      {
        catalog: "tortieWhitePatchColours",
        whenTrait: "tortie",
        condition: "nonEmptyList",
      },
    ],
  },
  capabilities: {
    display: true,
    edit: "select",
    reveal: {
      strategy: "single",
      timingKey: "whitePatchesTint",
      defaultSteps: 6,
      spin: { order: 100, label: "White Patch Tint" },
    },
    evolution: "replace",
    inherit: "mutate",
    settings: false,
  },
});

const vitiligo = defineCatTrait({
  id: "vitiligo",
  label: "Vitiligo",
  order: 100,
  value: stringValue({ required: false, catalog: "vitiligo" }),
  legacy: { strategy: "direct", key: "vitiligo" },
  render: {
    kind: "operation",
    operationId: "vitiligo",
    layerId: "vitiligo",
    strategy: "spriteLayer",
    version: 1,
    after: ["points"],
    reads: ["vitiligo"],
    config: {
      valueTrait: "vitiligo",
      spriteFamily: "white",
      diagnosticPrefix: "vitiligo",
    },
  },
  gacha: {
    strategy: "catalogChoice",
    catalog: "vitiligo",
    optionalProbability: 0.5,
    dependsOn: ["whitePatches"],
    gate: { group: "whitePatchGroup", probability: 0.5 },
  },
  capabilities: {
    display: true,
    edit: "select",
    reveal: {
      strategy: "single",
      timingKey: "vitiligo",
      defaultSteps: 6,
      spin: { order: 110 },
    },
    evolution: "replace",
    inherit: "mutate",
    settings: false,
  },
});

const eyeColour = defineCatTrait({
  id: "eyeColour",
  label: "Eyes",
  order: 110,
  value: stringValue({
    required: true,
    default: "BLUE",
    catalog: "eyeColours",
  }),
  legacy: { strategy: "direct", key: "eyeColour" },
  render: {
    kind: "operation",
    operationId: "eyes",
    layerId: "eyes",
    strategy: "eyes",
    version: 1,
    after: ["vitiligo"],
    reads: ["eyeColour", "eyeColour2"],
    config: {},
  },
  gacha: {
    strategy: "catalogChoice",
    catalog: "eyeColours",
    dependsOn: ["pose"],
  },
  capabilities: {
    display: true,
    edit: "select",
    reveal: {
      strategy: "single",
      timingKey: "eyeColour",
      defaultSteps: 8,
      spin: { order: 30 },
    },
    evolution: "preserve",
    inherit: "mutate",
    settings: false,
  },
});

const eyeColour2 = defineCatTrait({
  id: "eyeColour2",
  label: "Second eye colour",
  order: 120,
  value: stringValue({ required: false, catalog: "eyeColours" }),
  legacy: { strategy: "direct", key: "eyeColour2" },
  render: { kind: "input", operationId: "eyes" },
  gacha: {
    strategy: "catalogChoice",
    catalog: "eyeColours",
    optionalProbability: 0.5,
    includeUnsetChoice: true,
    dependsOn: ["eyeColour"],
  },
  capabilities: {
    display: true,
    edit: "select",
    reveal: {
      strategy: "single",
      timingKey: "eyeColour2",
      defaultSteps: 6,
      spin: { order: 40, label: "Eye Colour 2" },
    },
    evolution: "replace",
    inherit: "mutate",
    settings: false,
  },
});

const scars = defineCatTrait({
  id: "scars",
  label: "Scars",
  order: 130,
  value: stringListValue({
    required: false,
    default: [],
    catalog: "scars",
    maxItems: 10,
    unique: true,
  }),
  legacy: { strategy: "list", key: "scars", singleKey: "scar" },
  render: [
    {
      kind: "operation",
      operationId: "scarsPrimary",
      layerId: "scarsPrimary",
      strategy: "scarPrimary",
      version: 1,
      after: ["eyes"],
      reads: ["scars"],
      config: {},
    },
    {
      kind: "operation",
      operationId: "scarsSecondary",
      layerId: "scarsSecondary",
      strategy: "scarSecondary",
      version: 1,
      after: ["skin"],
      reads: ["scars"],
      config: {},
    },
  ],
  gacha: {
    strategy: "slotList",
    catalog: "scars",
    count: {
      strategy: "weightedDiscrete",
      weights: { "0": 1, "1": 1, "2": 1, "3": 1 },
      min: 0,
      max: 3,
    },
    fillProbability: 0.5,
    unique: true,
    dependsOn: ["pose"],
    availableForPose: true,
  },
  capabilities: {
    display: true,
    edit: "list",
    reveal: {
      strategy: "slots",
      timingKey: "scar",
      defaultSteps: 10,
      spin: { order: 130, label: "Scar" },
    },
    evolution: "accumulate",
    inherit: "none",
    settings: true,
  },
});

const shading = defineCatTrait({
  id: "shading",
  label: "Shading",
  order: 140,
  value: booleanValue({ required: true, default: false }),
  legacy: { strategy: "direct", key: "shading" },
  render: {
    kind: "operation",
    operationId: "shading",
    layerId: "tint",
    strategy: "booleanSpriteLayer",
    version: 1,
    after: ["scarsPrimary"],
    reads: ["shading"],
    config: {
      valueTrait: "shading",
      spriteKeys: ["shaders"],
      blend: "multiply",
      diagnostic: "shading",
    },
  },
  gacha: { strategy: "boolean", probability: 0 },
  capabilities: {
    display: true,
    edit: "toggle",
    reveal: {
      strategy: "single",
      timingKey: "shading",
      defaultSteps: 2,
      spin: false,
    },
    evolution: "preserve",
    inherit: "none",
    settings: false,
  },
});

const lighting = defineCatTrait({
  id: "lighting",
  label: "Lighting",
  order: 150,
  value: booleanValue({ required: false, default: false }),
  legacy: { strategy: "direct", key: "lighting" },
  render: {
    kind: "operation",
    operationId: "lighting",
    layerId: "lighting",
    strategy: "booleanSpriteLayer",
    version: 1,
    after: ["shading"],
    reads: ["lighting"],
    config: {
      valueTrait: "lighting",
      spriteKeys: ["lighting"],
      blend: "alpha",
      diagnostic: "lighting",
    },
  },
  gacha: { strategy: "none" },
  capabilities: {
    display: true,
    edit: "toggle",
    reveal: false,
    evolution: "preserve",
    inherit: "none",
    settings: false,
  },
});

const darkForest = defineCatTrait({
  id: "darkForest",
  label: "Dark Forest",
  order: 160,
  value: booleanValue({ required: false, default: false }),
  legacy: {
    strategy: "booleanAlias",
    key: "darkForest",
    aliases: ["darkMode"],
  },
  render: {
    kind: "operation",
    operationId: "darkForest",
    layerId: "tint",
    strategy: "solidMultiply",
    version: 1,
    after: ["lighting"],
    reads: ["darkForest"],
    config: {
      valueTrait: "darkForest",
      colour: [120, 30, 30, 200],
      diagnostic: "darkForest",
    },
  },
  gacha: { strategy: "boolean", probability: 0 },
  capabilities: {
    display: true,
    edit: "toggle",
    reveal: {
      strategy: "single",
      timingKey: "darkForest",
      defaultSteps: 2,
      spin: false,
    },
    evolution: "preserve",
    inherit: "none",
    settings: false,
  },
});

const dead = defineCatTrait({
  id: "dead",
  label: "StarClan",
  order: 170,
  value: booleanValue({ required: false, default: false }),
  legacy: { strategy: "direct", key: "dead" },
  render: {
    kind: "operation",
    operationId: "lineart",
    layerId: "lineart",
    strategy: "lineart",
    version: 1,
    after: ["darkForest"],
    reads: ["dead", "darkForest"],
    config: {},
  },
  gacha: { strategy: "boolean", probability: 0 },
  capabilities: {
    display: true,
    edit: "toggle",
    reveal: false,
    evolution: "preserve",
    inherit: "none",
    settings: false,
  },
});

const skinColour = defineCatTrait({
  id: "skinColour",
  label: "Skin",
  order: 180,
  value: stringValue({
    required: true,
    default: "PINK",
    catalog: "skinColours",
  }),
  legacy: { strategy: "direct", key: "skinColour" },
  render: {
    kind: "operation",
    operationId: "skin",
    layerId: "skin",
    strategy: "spriteLayer",
    version: 1,
    after: ["lineart"],
    reads: ["skinColour"],
    config: {
      valueTrait: "skinColour",
      spriteFamily: "skin",
      diagnosticPrefix: "skin",
    },
  },
  gacha: {
    strategy: "catalogChoice",
    catalog: "skinColours",
    dependsOn: ["pose"],
  },
  capabilities: {
    display: true,
    edit: "select",
    reveal: {
      strategy: "single",
      timingKey: "skinColour",
      defaultSteps: 5,
      spin: { order: 70 },
    },
    evolution: "preserve",
    inherit: "mutate",
    settings: false,
  },
});

const accessories = defineCatTrait({
  id: "accessories",
  label: "Accessories",
  order: 190,
  value: stringListValue({
    required: false,
    default: [],
    catalog: "accessories",
    maxItems: 10,
    unique: true,
  }),
  legacy: { strategy: "list", key: "accessories", singleKey: "accessory" },
  render: {
    kind: "operation",
    operationId: "accessories",
    layerId: "accessories",
    strategy: "catalogSpriteList",
    version: 1,
    after: ["scarsSecondary"],
    reads: ["accessories"],
    config: {
      valueTrait: "accessories",
      catalog: "accessories",
      resolver: "accessory",
    },
  },
  gacha: {
    strategy: "slotList",
    catalog: "accessories",
    count: {
      strategy: "weightedDiscrete",
      weights: { "0": 1, "1": 1, "2": 1, "3": 1, "4": 1 },
      min: 0,
      max: 4,
    },
    fillProbability: 0.5,
    unique: true,
    dependsOn: ["pose"],
    availableForPose: true,
  },
  capabilities: {
    display: true,
    edit: "list",
    reveal: {
      strategy: "slots",
      timingKey: "accessory",
      defaultSteps: 12,
      spin: { order: 120, label: "Accessory" },
    },
    evolution: "accumulate",
    inherit: "none",
    settings: true,
  },
});

const reverse = defineCatTrait({
  id: "reverse",
  label: "Reverse",
  order: 200,
  value: booleanValue({ required: true, default: false }),
  legacy: { strategy: "direct", key: "reverse" },
  render: {
    kind: "operation",
    operationId: "reverse",
    layerId: "transform",
    strategy: "globalMirror",
    version: 1,
    after: ["accessories"],
    reads: ["reverse"],
    config: { valueTrait: "reverse", affectsPreviousLayers: true },
  },
  gacha: { strategy: "boolean", probability: 0.5 },
  capabilities: {
    display: true,
    edit: "toggle",
    reveal: {
      strategy: "single",
      timingKey: "reverse",
      defaultSteps: 2,
      spin: false,
    },
    evolution: "preserve",
    inherit: "none",
    settings: false,
  },
});

export const catSystem = defineCatSystem({
  schemaVersion: CAT_SCHEMA_VERSION,
  catalogs: {
    poses: { source: "poseData", key: "poses" },
    randomPoses: {
      source: "poseData",
      key: "renderablePoseNames",
      randomSelectable: true,
    },
    pelts: { source: "peltInfo", keys: ["patterns"] },
    coatPatterns: { source: "coatPatterns" },
    coatChoices: { source: "composite", catalogs: ["pelts", "coatPatterns"] },
    baseColours: { source: "peltInfo", keys: ["colors"] },
    paletteColours: { source: "paletteColours" },
    colours: {
      source: "composite",
      catalogs: ["baseColours", "paletteColours"],
    },
    eyeColours: { source: "peltInfo", keys: ["eyes"] },
    skinColours: { source: "peltInfo", keys: ["skin"] },
    whitePatches: { source: "peltInfo", keys: ["white"] },
    points: { source: "peltInfo", keys: ["point_markings"] },
    vitiligo: { source: "peltInfo", keys: ["vitiligo"] },
    scars: { source: "peltInfo", keys: ["scars1", "scars2", "scars3"] },
    tortieMasks: { source: "peltInfo", keys: ["tortie_masks"] },
    accessories: { source: "peltInfo", keys: ["accessories"] },
    tints: { source: "tintData", file: "tint" },
    whiteTints: { source: "tintData", file: "white_patches_tint" },
    whitePatchColours: {
      source: "composite",
      catalogs: ["whiteTints", "baseColours", "paletteColours"],
      selectableCatalogs: ["whiteTints"],
    },
    tortieWhitePatchColours: {
      source: "composite",
      catalogs: ["whiteTints", "baseColours", "paletteColours"],
      selectableCatalogs: ["whiteTints"],
    },
  },
  traits: [
    pose,
    pelt,
    coatPattern,
    colour,
    tortie,
    tint,
    whitePatches,
    points,
    whitePatchesTint,
    vitiligo,
    eyeColour,
    eyeColour2,
    scars,
    shading,
    lighting,
    darkForest,
    dead,
    skinColour,
    accessories,
    reverse,
  ] as const,
  aliases: {
    accessory: "accessories",
    scar: "scars",
    darkMode: "darkForest",
    sprite: "pose",
  },
  tombstones: {},
});

export type CatSystem = typeof catSystem;
export type CatTraitId = CatSystem["traits"][number]["id"];
